### ISSUE TITLE
Can't walk dependency graph

### ISSUE THREAD

**Issue by Ixluxi** [infosum/cypress-tags#258]
Hello,

Me and someone else have encountered a "can't walk dependency graph" issue.

My issue: [https://stackoverflow.com/questions/77482595/cypress-azure-cant-walk-dependency-graph-enoent-no-such-file-or-directory-l](url)

Their issue: [https://github.com/aws/aws-sdk-js-v3/issues/5349](url)

Their issue seems to have gotten to the bottom of it (I can confirm that after having removed cypress-tags (v1.2.2), I no longer encounter the issue).

cypress-tags was working for me - either before I started using Azure or before I upgraded to Cypress 13+. Can't remember the last Cypress version it worked on. I'm now on Cypress 13.5.1

Thanks

**Comment by AshMcConnell** [comment]
I'm getting this on Cypress 10.11.0 only some test files error though.  I'm not sure what the pattern is.  I'm just running it locally, so Azure wasn't involved.

```
Can't walk dependency graph: Cannot find module '@angular/core' from ' ......
```

**Comment by vincezipparro** [comment]
Also, getting this error

**Comment by gsjardim** [comment]
I'm getting this error too, and I notice that it is the presence of this line `on('file:preprocessor', tagify(config)); ` in the cypress.config.ts that breaks the "dependency graph".

`Error: Can't walk dependency graph: Cannot find module 'cypress/helper-functions/browser-config' from 'c:\ice\FrontEnd\ts\test\integration-tests\test-cases\test-common.ts'
    required by c:\ice\FrontEnd\ts\test\integration-tests\test-cases\test-common.ts
    at c:\ice\FrontEnd\node_modules\resolve\lib\async.js:146:35
    at processDirs (c:\ice\FrontEnd\node_modules\resolve\lib\async.js:299:39)
    at isdir (c:\ice\FrontEnd\node_modules\resolve\lib\async.js:306:32)
    at c:\ice\FrontEnd\node_modules\resolve\lib\async.js:34:69
    at callback (C:\Users\gjardim\AppData\Local\Cypress\Cache\13.15.0\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\polyfills.js:299:20)
    at callback (C:\Users\gjardim\AppData\Local\Cypress\Cache\13.15.0\Cypress\resources\app\node_modules\@packages\server\node_modules\graceful-fs\polyfills.js:299:20)
    at FSReqCallback.oncomplete (node:fs:199:21)`

If I remove that line, everything works. Except the cypress-tags, obviously...

Any solutions to this?

**Comment by Ixluxi** [comment]
@gsjardim It's been a while since I had the issue and I feel like the reason I stopped having it was because I moved to using badeball/cypress-cucumber-preprocessor which includes test tag functionality. Granted, this might not be very helpful to you if you don't want to use Cucumber, but just thought I'd mention it.
